// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseFolder():Promise<string>;

export function GetConfig():Promise<main.UIConfig>;

export function GetConfigPath():Promise<string>;

export function GetLogs(arg1:number):Promise<Array<string>>;

export function GetServiceStatus():Promise<main.ServiceStatus>;

export function GetStats():Promise<main.BackupStats>;

export function RunBackupNow():Promise<string>;

export function SaveConfig(arg1:main.UIConfig):Promise<string>;

export function SetConfigPath(arg1:string):Promise<void>;

export function StartService():Promise<string>;

export function StopService():Promise<string>;
