// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function RunBackupNow() {
  return window['go']['main']['App']['RunBackupNow']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetConfigPath(arg1) {
  return window['go']['main']['App']['SetConfigPath'](arg1);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}
