; BackupSMC Agent — Inno Setup 6 installer script
; SMC Soluciones
; https://smcsoluciones.com

#define AppName      "BackupSMC"
#define AppVersion   "0.4.0"
#define AppPublisher "SMC Soluciones"
#define AppURL       "https://smcsoluciones.com"
#define AppExeName   "backupsmc-agent.exe"
#define GUIExeName   "BackupSMC.exe"
#define ServiceName  "BackupSMC"
#define DefaultCfg   "agent.yaml"

[Setup]
AppId={{A7B3C2D1-4E5F-6A7B-8C9D-0E1F2A3B4C5D}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\BackupSMC\Agent
DefaultGroupName=BackupSMC
AllowNoIcons=yes
; OutputDir is relative to the .iss file location
OutputDir=..\dist
OutputBaseFilename=BackupSMC-Agent-{#AppVersion}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
; Require Admin — needed to install Windows service
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=
; Minimum Windows 10
MinVersion=10.0
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#AppExeName}
UninstallDisplayName={#AppName} {#AppVersion}
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "installservice";   Description: "Install and start BackupSMC as a Windows Service (recommended)"; GroupDescription: "Windows Service:"; Flags: checkedonce
Name: "desktopicon";      Description: "Create a &desktop shortcut for BackupSMC"; GroupDescription: "Additional icons:"

[Files]
; Agent service binary
Source: "..\backupsmc-agent.exe";              DestDir: "{app}";  Flags: ignoreversion
; GUI desktop app
Source: "..\BackupSMC.exe";                    DestDir: "{app}";  Flags: ignoreversion
; Reference config — always install alongside but agent.yaml is generated by installer
Source: "..\agent.example.yaml";               DestDir: "{app}";  Flags: ignoreversion

[Dirs]
; Create logs directory
Name: "{app}\logs"
; Default local backup destination (user can change in config)
Name: "{app}\backups"

[Icons]
Name: "{group}\BackupSMC";            Filename: "{app}\{#GUIExeName}";   WorkingDir: "{app}"
Name: "{group}\Edit Configuration";   Filename: "notepad.exe";            Parameters: "{app}\{#DefaultCfg}"
Name: "{group}\Uninstall BackupSMC";  Filename: "{uninstallexe}"
Name: "{commondesktop}\BackupSMC";    Filename: "{app}\{#GUIExeName}";   WorkingDir: "{app}"; Tasks: desktopicon

[Run]
; Stop service before upgrade (ignore errors if not installed)
Filename: "{app}\{#AppExeName}"; Parameters: "stop-service";      Flags: runhidden nowait skipifdoesntexist; StatusMsg: "Stopping existing service..."

; Install and start the Windows service
Filename: "{app}\{#AppExeName}"; Parameters: "install-service -c ""{app}\{#DefaultCfg}"""; \
    Flags: runhidden; StatusMsg: "Installing Windows service..."; \
    Tasks: installservice

Filename: "{app}\{#AppExeName}"; Parameters: "start-service"; \
    Flags: runhidden; StatusMsg: "Starting BackupSMC service..."; \
    Tasks: installservice

; Post-install: launch GUI
Filename: "{app}\{#GUIExeName}"; \
    Description: "Launch BackupSMC"; \
    Flags: postinstall nowait skipifsilent unchecked

; Post-install: open config file for review
Filename: "notepad.exe"; Parameters: "{app}\{#DefaultCfg}"; \
    Description: "Open configuration file to review settings"; \
    Flags: postinstall nowait skipifsilent unchecked

[UninstallRun]
; Stop then uninstall the service gracefully before files are removed
Filename: "{app}\{#AppExeName}"; Parameters: "stop-service";      Flags: runhidden skipifdoesntexist; RunOnceId: "StopSvc"
Filename: "{app}\{#AppExeName}"; Parameters: "uninstall-service";  Flags: runhidden skipifdoesntexist; RunOnceId: "RemoveSvc"

[Code]
// ---------------------------------------------------------------------------
// Generates a template agent.yaml on fresh install (skipped on upgrade).
// All configuration is done after install via the BackupSMC web UI or by
// editing the yaml directly.
// ---------------------------------------------------------------------------

procedure WriteConfigTemplate;
var
  CfgPath: String;
  Content: String;
begin
  CfgPath := ExpandConstant('{app}\{#DefaultCfg}');

  // Never overwrite an existing config (upgrade path).
  if FileExists(CfgPath) then Exit;

  Content :=
    '# BackupSMC Agent Configuration — v{#AppVersion}' + #13#10 +
    '# Configure server URL and token via the BackupSMC web interface,' + #13#10 +
    '# or edit this file directly and restart the service.' + #13#10 +
    '' + #13#10 +
    'server:' + #13#10 +
    '  url: "http://localhost:8000"   # CHANGE: URL of your BackupSMC server' + #13#10 +
    '  api_token: ""                  # CHANGE: paste the agent token from the web UI' + #13#10 +
    '  timeout: 30s' + #13#10 +
    '' + #13#10 +
    'backup:' + #13#10 +
    '  source_paths: []               # Configure via web UI or add paths here' + #13#10 +
    '  exclude_patterns:' + #13#10 +
    '    - "*.tmp"' + #13#10 +
    '    - "*.log"' + #13#10 +
    '    - "$RECYCLE.BIN/**"' + #13#10 +
    '    - "System Volume Information/**"' + #13#10 +
    '    - "pagefile.sys"' + #13#10 +
    '  encryption_passphrase: ""      # CHANGE: min. 16 characters, keep it safe' + #13#10 +
    '  use_vss: true' + #13#10 +
    '  incremental: true' + #13#10 +
    '  schedule_interval: 24h' + #13#10 +
    '  verify_after_backup: false' + #13#10 +
    '  throttle_mbps: 0' + #13#10 +
    '' + #13#10 +
    'destination:' + #13#10 +
    '  type: local' + #13#10 +
    '  local_path: "' + ExpandConstant('{app}\backups') + '"' + #13#10 +
    '' + #13#10 +
    'retention:' + #13#10 +
    '  days: 30' + #13#10 +
    '  gfs:' + #13#10 +
    '    enabled: false' + #13#10 +
    '    keep_daily: 7' + #13#10 +
    '    keep_weekly: 4' + #13#10 +
    '    keep_monthly: 12' + #13#10 +
    '' + #13#10 +
    'retry:' + #13#10 +
    '  max_attempts: 3' + #13#10 +
    '  initial_delay: 1s' + #13#10 +
    '' + #13#10 +
    'log:' + #13#10 +
    '  level: info' + #13#10 +
    '  format: console' + #13#10 +
    '  path: stdout' + #13#10 +
    '' + #13#10 +
    'notify:' + #13#10 +
    '  email:' + #13#10 +
    '    enabled: false' + #13#10 +
    '    smtp_host: ""' + #13#10 +
    '    smtp_port: 587' + #13#10 +
    '    username: ""' + #13#10 +
    '    password: ""' + #13#10 +
    '    from: ""' + #13#10 +
    '    to: []' + #13#10 +
    '    on_failure: true' + #13#10 +
    '    on_success: false' + #13#10;

  SaveStringToFile(CfgPath, Content, False);
end;

// ---------------------------------------------------------------------------
// ssInstall: write template config. ssDone: show completion message.
// ---------------------------------------------------------------------------
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
    WriteConfigTemplate;

  if CurStep = ssDone then
    MsgBox(
      '{#AppName} {#AppVersion} installed successfully.' + #13#10#13#10 +
      'Next steps:' + #13#10 +
      '  1. Open the BackupSMC web interface.' + #13#10 +
      '  2. Copy the Agent API Token from Settings.' + #13#10 +
      '  3. Edit the configuration file and set server URL, token and passphrase:' + #13#10 +
      '     ' + ExpandConstant('{app}\{#DefaultCfg}') + #13#10#13#10 +
      '  4. Start the service:  backupsmc-agent.exe start-service',
      mbInformation, MB_OK
    );
end;
